"""Update User model

Revision ID: b5c83666d332
Revises: a690ad5c2daf
Create Date: 2024-11-03 10:56:19.591784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5c83666d332'
down_revision: Union[str, None] = 'a690ad5c2daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_users_first_name', table_name='users')
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.drop_index('ix_users_last_name', table_name='users')
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.create_index('ix_users_last_name', 'users', ['last_name'], unique=True)
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.create_index('ix_users_first_name', 'users', ['first_name'], unique=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
